'use client';
import { useCallback, useEffect, useState } from 'react';
import { exerciseApi } from './api';
import { ExerciseButton, ExerciseInput } from './controls';
type Classroom = { id: number; name: string; _count: { members: number } };
export default function ClassroomManager() {
  const [items, setItems] = useState<Classroom[]>([]), [name, setName] = useState(''), [selected, setSelected] = useState<number | null>(null), [members, setMembers] = useState<{ student: { username: string }; groupName: string }[]>([]), [username, setUsername] = useState(''), [groupName, setGroupName] = useState(''), [error, setError] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [rosterPage, setRosterPage] = useState(1), [rosterTotal, setRosterTotal] = useState(0);
  const load = useCallback(async () => { const d = await exerciseApi<{ items: Classroom[]; total: number }>(`/api/exercises/classrooms?page=${page}`); setItems(d.items); setTotal(d.total); if (selected) { const c = await exerciseApi<{ members: typeof members; total: number }>(`/api/exercises/classrooms/${selected}?page=${rosterPage}`); setMembers(c.members); setRosterTotal(c.total); } }, [page, selected, rosterPage]);
  useEffect(() => { void load().catch(e => setError(e.message)); }, [load]);
  return <main className="mx-auto grid max-w-4xl gap-5 px-4 py-8"><h1 className="text-3xl font-bold">Lớp học và nhóm</h1><ExerciseInput label="Tên lớp mới" value={name} onChange={e => setName(e.target.value)} /><ExerciseButton onClick={() => void exerciseApi('/api/exercises/classrooms', 'POST', { name }).then(() => { setName(''); void load(); }).catch(e => setError(e.message))}>Tạo lớp</ExerciseButton><div className="flex flex-wrap gap-3">{items.map(c => <ExerciseButton key={c.id} onClick={() => { setSelected(c.id); setRosterPage(1); }}>{c.name} · {c._count.members} học sinh · #{c.id}</ExerciseButton>)}</div><div className="flex gap-3"><ExerciseButton disabled={page === 1} onClick={() => setPage(page - 1)}>Trước</ExerciseButton><ExerciseButton disabled={page * 20 >= total} onClick={() => setPage(page + 1)}>Tiếp</ExerciseButton></div>{selected && <section className="min-w-0 grid gap-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Danh sách lớp #{selected}</h2><ExerciseInput label="Tên đăng nhập học sinh" value={username} onChange={e => setUsername(e.target.value)} /><ExerciseInput label="Nhóm (tùy chọn)" value={groupName} onChange={e => setGroupName(e.target.value)} /><ExerciseButton onClick={() => void exerciseApi(`/api/exercises/classrooms/${selected}`, 'PUT', { username, groupName }).then(() => { setUsername(''); void load(); }).catch(e => setError(e.message))}>Thêm / cập nhật học sinh</ExerciseButton>{members.map(m => <div key={m.student.username} className="flex flex-wrap items-center justify-between gap-3"><span>{m.student.username} · {m.groupName || 'Chưa chia nhóm'}</span><ExerciseButton onClick={() => void exerciseApi(`/api/exercises/classrooms/${selected}`, 'PUT', { username: m.student.username, groupName: '', remove: true }).then(load).catch(e => setError(e.message))}>Bỏ khỏi lớp</ExerciseButton></div>)}<div className="flex gap-3"><ExerciseButton disabled={rosterPage === 1} onClick={() => setRosterPage(rosterPage - 1)}>Trước</ExerciseButton><ExerciseButton disabled={rosterPage * 50 >= rosterTotal} onClick={() => setRosterPage(rosterPage + 1)}>Tiếp</ExerciseButton></div></section>}{error && <p role="alert">{error}</p>}</main>;
}
