'use client';
import Link from 'next/link';

import { useEffect, useState } from 'react';
import { exerciseApi } from './api';
import { ExerciseButton, ExerciseInput } from './controls';
type Progress = { completionRate: number; averageScore: number; studentsNeedHelp: { username: string; average: number }[]; topExercises: { title: string; completed: number }[]; completed: number; assigned: number; streak: number; skills: { skill: string; completed: number; averageScore: number }[]; xp: number; stars: number; level: number; badges: string[]; count: number; attempts: { id: number; student: { username: string }; exercise: { title: string; skill: string }; score: number | null; totalScore: number | null; submittedAt: string | null; needsReview: boolean }[] };
export default function ExerciseProgress({ teacher = false }: { teacher?: boolean }) {
  const [data, setData] = useState<Progress | null>(null), [error, setError] = useState(''), [page, setPage] = useState(1), [student, setStudent] = useState('');
  useEffect(() => { void exerciseApi<Progress>(`/api/exercises/progress?teacher=${teacher ? 1 : 0}&page=${page}&student=${encodeURIComponent(student)}`).then(setData).catch(e => setError(e.message)); }, [teacher, page, student]);
  return <main className="mx-auto grid max-w-5xl gap-6 px-4 py-8"><h1 className="text-3xl font-black">{teacher ? 'Kết quả học sinh' : 'Hành trình của em'}</h1>{teacher && <ExerciseInput label="Lọc theo tên đăng nhập học sinh" value={student} onChange={e => { setStudent(e.target.value); setPage(1); }} />}{error && <p role="alert">{error}</p>}{data && <>{!teacher && <div className="rounded-3xl bg-white p-6 text-xl font-bold">⭐ {data.stars} sao · {data.xp} XP · Level {data.level}<p className="mt-4">{data.badges.join(' · ')}</p></div>}<p>Đã hoàn thành: {data.completed} lượt · Bài đã giao: {data.assigned} · Chuỗi học: {data.streak} ngày · Hoàn thành bài giao: {data.completionRate}% · Điểm trung bình: {data.averageScore}%</p>{teacher && <><section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Học sinh cần hỗ trợ</h2>{data.studentsNeedHelp.map(s => <p key={s.username}>{s.username} · {s.average}%</p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Bài được luyện nhiều</h2>{data.topExercises.map(e => <p key={e.title}>{e.title} · {e.completed} lượt</p>)}</section></>}<div className="min-w-0 grid gap-3 sm:grid-cols-2">{data.skills.map(s => <article key={s.skill} className="rounded-2xl border bg-white p-4"><h2 className="font-bold">{s.skill}</h2><p>{s.averageScore}% · {s.completed} lượt hoàn thành</p><p>{s.averageScore >= 80 ? 'Kỹ năng tốt' : s.averageScore < 60 ? 'Cần luyện thêm' : 'Đang tiến bộ'}</p></article>)}</div><div className="min-w-0 grid gap-3">{data.attempts.map(a => <article key={a.id} className="flex flex-wrap justify-between gap-3 rounded-2xl border bg-white p-5"><div><h2 className="font-bold">{a.exercise.title}</h2><p>{a.student.username} · {a.exercise.skill}</p></div><div>{teacher && a.submittedAt && <Link className="text-sky-700" href={`/teacher/exercises/attempts/${a.id}`}>Xem / chấm bài →</Link>}<p>{a.submittedAt ? a.needsReview ? 'Chờ giáo viên chấm' : a.score === null ? 'Đã nộp' : `${a.score} / ${a.totalScore}` : 'Đang làm'}</p></div></article>)}</div><div className="flex gap-4"><ExerciseButton disabled={page === 1} onClick={() => setPage(page - 1)}>Trước</ExerciseButton><ExerciseButton disabled={page * 50 >= data.count} onClick={() => setPage(page + 1)}>Tiếp</ExerciseButton></div></>}</main>;
}

