'use client';
import { useEffect, useState } from 'react';
import { Question, SKILLS, QUESTION_TYPES } from '@/lib/exercises/contracts';
import { exerciseApi } from './api';
import { ExerciseButton, fieldClass } from './controls';
export default function QuestionBank({ onAdd }: { onAdd: (questions: Question[]) => void }) {
  const [filters, setFilters] = useState({ grade: '', skill: '', type: '', difficulty: '', unit: '', lesson: '', q: '' }), [page, setPage] = useState(1), [items, setItems] = useState<{ question: Question; title: string }[]>([]), [totalPages, setTotalPages] = useState(1), [error, setError] = useState(''), [count, setCount] = useState(10);
  useEffect(() => { const params = new URLSearchParams({ ...filters, page: String(page) }); void exerciseApi<{ items: typeof items; totalPages: number }>(`/api/exercises/question-bank?${params}`).then(d => { setItems(d.items); setTotalPages(d.totalPages); }).catch(e => setError(e.message)); }, [filters, page]);
  const options = { grade: ['1', '2', '3', '4', '5', '6', '7', '8', '9'], skill: [...SKILLS], type: [...QUESTION_TYPES], difficulty: ['easy', 'medium', 'hard'] };
  const copy = (qs: Question[]) => onAdd(qs.map(q => ({ ...structuredClone(q), id: crypto.randomUUID() })));
  return <section className="min-w-0 grid gap-4 rounded-xl border p-4"><h3 className="text-xl font-bold">Ngân hàng câu hỏi</h3><div className="min-w-0 grid gap-3 sm:grid-cols-2">{(Object.keys(options) as (keyof typeof options)[]).map(k => <select key={k} aria-label={`Bank ${k}`} className={fieldClass} value={filters[k]} onChange={e => { setFilters({ ...filters, [k]: e.target.value }); setPage(1); }}><option value="">{k}: tất cả</option>{options[k].map(v => <option key={v}>{v}</option>)}</select>)}{(['unit', 'lesson', 'q'] as const).map(k => <input key={k} aria-label={`Bank ${k}`} placeholder={k} className={fieldClass} value={filters[k]} onChange={e => { setFilters({ ...filters, [k]: e.target.value }); setPage(1); }} />)}</div>{error && <p role="alert">{error}</p>}<div className="max-h-96 overflow-auto">{items.map((item, i) => <div key={i} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><p className="font-bold">{item.question.prompt}</p><p className="text-sm">{item.title}</p></div><ExerciseButton onClick={() => copy([item.question])}>Thêm</ExerciseButton></div>)}</div><div className="flex flex-wrap items-center gap-3"><ExerciseButton disabled={page <= 1} onClick={() => setPage(page - 1)}>Trước</ExerciseButton><span>Trang {page}/{totalPages || 1}</span><ExerciseButton disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Tiếp</ExerciseButton></div><label>Số câu lấy ngẫu nhiên từ kết quả trang này<input className={fieldClass} type="number" min={1} max={100} value={count} onChange={e => setCount(Math.max(1, Math.min(100, Number(e.target.value))))} /></label><ExerciseButton disabled={!items.length} onClick={() => { const pool = [...items]; for (let i = pool.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [pool[i], pool[j]] = [pool[j], pool[i]]; } copy(pool.slice(0, count).map(i => i.question)); }}>Thêm ngẫu nhiên {Math.min(count, items.length)} câu</ExerciseButton></section>;
}
