'use client';
import { useEffect, useState } from 'react';
import { Answers, Question } from '@/lib/exercises/contracts';
import { exerciseApi } from './api';
import { ExerciseButton, fieldClass } from './controls';
export default function TeacherReview({ id }: { id: number }) {
  const [attempt, setAttempt] = useState<{ snapshot: Question[]; answers: Answers; revision: number } | null>(null), [grades, setGrades] = useState<Record<string, { score: number; feedback: string }>>({}), [message, setMessage] = useState('');
  useEffect(() => { void exerciseApi<{ snapshot: Question[]; answers: Answers; manualGrades: typeof grades; revision: number }>(`/api/attempts/${id}/review`).then(a => { setAttempt(a); setGrades(a.manualGrades); }).catch(e => setMessage(e.message)); }, [id]);
  return <main className="mx-auto grid max-w-3xl gap-6 px-4 py-8"><h1 className="text-3xl font-bold">Chấm bài #{id}</h1>{attempt?.snapshot.map(q => <article key={q.id} className="min-w-0 grid gap-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">{q.prompt}</h2>{q.type === 'speaking' && typeof attempt.answers[q.id] === 'string' && String(attempt.answers[q.id]).startsWith('/api/exercises/media/') ? <audio controls src={String(attempt.answers[q.id])} aria-label="Bài nói học sinh" /> : <p className="whitespace-pre-wrap">Bài làm: {JSON.stringify(attempt.answers[q.id] ?? '')}</p>}{['writing', 'speaking'].includes(q.type) ? <><label>Điểm (0–{q.score})<input className={fieldClass} type="number" min={0} max={q.score} value={grades[q.id]?.score ?? ''} onChange={e => setGrades({ ...grades, [q.id]: { score: Number(e.target.value), feedback: grades[q.id]?.feedback ?? '' } })} /></label><label>Nhận xét<textarea className={fieldClass} value={grades[q.id]?.feedback ?? ''} onChange={e => setGrades({ ...grades, [q.id]: { score: grades[q.id]?.score ?? 0, feedback: e.target.value } })} /></label></> : <p>Đáp án: {JSON.stringify(q.type === 'matching' ? q.pairs : q.acceptedAnswers)}</p>}</article>)}<ExerciseButton disabled={!attempt} onClick={() => { if (attempt) void exerciseApi<{ revision: number; needsReview: boolean }>(`/api/attempts/${id}/review`, 'PUT', { manualGrades: grades, revision: attempt.revision }).then(r => { setAttempt({ ...attempt, revision: r.revision }); setMessage(r.needsReview ? 'Đã lưu. Còn câu chưa chấm.' : 'Đã chấm xong.'); }).catch(e => setMessage(e.message)); }}>Lưu điểm và nhận xét</ExerciseButton><p role="status">{message}</p></main>;
}
